CREATE TABLE IF NOT EXISTS dw.dim_date (
    date_key                integer PRIMARY KEY,
    full_date               date NOT NULL UNIQUE,
    annee                   smallint NOT NULL,
    trimestre              smallint NOT NULL CHECK (trimestre BETWEEN 1 AND 4),
    mois                    smallint NOT NULL CHECK (mois BETWEEN 1 AND 12),
    mois_nom                varchar(20) NOT NULL,
    annee_mois              char(7) NOT NULL,
    semaine_iso             smallint NOT NULL CHECK (semaine_iso BETWEEN 1 AND 53),
    jour                    smallint NOT NULL CHECK (jour BETWEEN 1 AND 31),
    jour_semaine_iso        smallint NOT NULL CHECK (jour_semaine_iso BETWEEN 1 AND 7),
    jour_nom                varchar(20) NOT NULL,
    est_weekend             boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS dw.dim_horaire (
    horaire_key             integer PRIMARY KEY,
    heure                   smallint,
    minute                  smallint,
    heure_libelle           char(5) NOT NULL,
    tranche_horaire         varchar(30) NOT NULL,
    periode_journee         varchar(20) NOT NULL,
    CONSTRAINT ck_dim_horaire_heure CHECK (heure IS NULL OR heure BETWEEN 0 AND 23),
    CONSTRAINT ck_dim_horaire_minute CHECK (minute IS NULL OR minute BETWEEN 0 AND 59)
);

CREATE TABLE IF NOT EXISTS dw.dim_localisation (
    localisation_key                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_commune                       varchar(5) NOT NULL UNIQUE,
    type_commune                       varchar(10) NOT NULL,
    code_commune_parente               varchar(5),
    commune                            varchar(200) NOT NULL,
    code_departement                   varchar(3) NOT NULL,
    departement                        varchar(200) NOT NULL,
    code_region                        varchar(3),
    region                             varchar(200) NOT NULL,
    population_municipale_2022         bigint,
    population_comptee_a_part_2022     bigint,
    population_totale_2022             bigint,
    CONSTRAINT ck_dim_localisation_population_municipale
        CHECK (population_municipale_2022 IS NULL OR population_municipale_2022 >= 0),
    CONSTRAINT ck_dim_localisation_population_totale
        CHECK (population_totale_2022 IS NULL OR population_totale_2022 >= 0)
);

CREATE TABLE IF NOT EXISTS dw.dim_route (
    route_key                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_profile_code        char(64) NOT NULL UNIQUE,
    categorie_route_code      smallint,
    categorie_route           varchar(100) NOT NULL,
    circulation_code          smallint,
    circulation               varchar(100) NOT NULL,
    nombre_voies              smallint,
    voie_reservee_code        smallint,
    voie_reservee             varchar(100) NOT NULL,
    profil_code               smallint,
    profil                    varchar(100) NOT NULL,
    trace_code                smallint,
    trace                     varchar(100) NOT NULL,
    surface_code              smallint,
    etat_surface              varchar(100) NOT NULL,
    infrastructure_code       smallint,
    infrastructure            varchar(100) NOT NULL,
    situation_code            smallint,
    situation                 varchar(100) NOT NULL,
    vitesse_maximale          smallint,
    tranche_vitesse           varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS dw.dim_circonstance (
    circonstance_key             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    circonstance_profile_code    char(64) NOT NULL UNIQUE,
    luminosite_code              smallint,
    luminosite                   varchar(100) NOT NULL,
    type_zone_code               smallint,
    type_zone                    varchar(100) NOT NULL,
    intersection_code            smallint,
    intersection                 varchar(100) NOT NULL,
    meteo_code                   smallint,
    meteo                        varchar(100) NOT NULL,
    collision_code               smallint,
    type_collision               varchar(150) NOT NULL
);

COMMENT ON TABLE dw.dim_date IS 'Calendrier analytique, une ligne par date.';
COMMENT ON TABLE dw.dim_horaire IS 'Une ligne par minute de la journée et un membre inconnu.';
COMMENT ON TABLE dw.dim_localisation IS 'Référentiel communal enrichi par le COG et les populations INSEE.';
COMMENT ON TABLE dw.dim_route IS 'Profils routiers distincts issus de la voie principale de chaque accident.';
COMMENT ON TABLE dw.dim_circonstance IS 'Combinaisons de circonstances générales des accidents.';

