CREATE TABLE IF NOT EXISTS dw.fact_accident (
    accident_key                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    num_acc                            varchar(20) NOT NULL UNIQUE,
    date_key                           integer NOT NULL DEFAULT 0,
    horaire_key                        integer NOT NULL DEFAULT 0,
    localisation_key                   bigint NOT NULL DEFAULT 0,
    route_key                          bigint NOT NULL DEFAULT 0,
    circonstance_key                   bigint NOT NULL DEFAULT 0,

    accident_count                     smallint NOT NULL DEFAULT 1 CHECK (accident_count = 1),
    nombre_vehicules                   integer NOT NULL DEFAULT 0 CHECK (nombre_vehicules >= 0),
    nombre_usagers                     integer NOT NULL DEFAULT 0 CHECK (nombre_usagers >= 0),
    nombre_victimes                    integer NOT NULL DEFAULT 0 CHECK (nombre_victimes >= 0),
    nombre_indemnes                    integer NOT NULL DEFAULT 0 CHECK (nombre_indemnes >= 0),
    nombre_tues                        integer NOT NULL DEFAULT 0 CHECK (nombre_tues >= 0),
    nombre_blesses_hospitalises        integer NOT NULL DEFAULT 0 CHECK (nombre_blesses_hospitalises >= 0),
    nombre_blesses_legers              integer NOT NULL DEFAULT 0 CHECK (nombre_blesses_legers >= 0),
    nombre_conducteurs                 integer NOT NULL DEFAULT 0 CHECK (nombre_conducteurs >= 0),
    nombre_passagers                   integer NOT NULL DEFAULT 0 CHECK (nombre_passagers >= 0),
    nombre_pietons                     integer NOT NULL DEFAULT 0 CHECK (nombre_pietons >= 0),
    nombre_vehicules_legers            integer NOT NULL DEFAULT 0 CHECK (nombre_vehicules_legers >= 0),
    nombre_deux_roues                  integer NOT NULL DEFAULT 0 CHECK (nombre_deux_roues >= 0),
    nombre_poids_lourds                integer NOT NULL DEFAULT 0 CHECK (nombre_poids_lourds >= 0),
    nombre_lieux_associes              integer NOT NULL DEFAULT 1 CHECK (nombre_lieux_associes >= 1),

    est_accident_mortel                boolean NOT NULL DEFAULT false,
    est_multi_voies                    boolean NOT NULL DEFAULT false,
    adresse                            text,
    voie_principale                    text,
    latitude                           numeric(10, 7),
    longitude                          numeric(10, 7),
    millesime_source                   smallint NOT NULL CHECK (millesime_source BETWEEN 2019 AND 2024),
    loaded_at                          timestamptz NOT NULL DEFAULT current_timestamp,

    CONSTRAINT fk_fact_accident_date
        FOREIGN KEY (date_key) REFERENCES dw.dim_date(date_key),
    CONSTRAINT fk_fact_accident_horaire
        FOREIGN KEY (horaire_key) REFERENCES dw.dim_horaire(horaire_key),
    CONSTRAINT fk_fact_accident_localisation
        FOREIGN KEY (localisation_key) REFERENCES dw.dim_localisation(localisation_key),
    CONSTRAINT fk_fact_accident_route
        FOREIGN KEY (route_key) REFERENCES dw.dim_route(route_key),
    CONSTRAINT fk_fact_accident_circonstance
        FOREIGN KEY (circonstance_key) REFERENCES dw.dim_circonstance(circonstance_key),
    CONSTRAINT ck_fact_accident_latitude
        CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_fact_accident_longitude
        CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_fact_accident_victimes
        CHECK (nombre_victimes = nombre_tues + nombre_blesses_hospitalises + nombre_blesses_legers),
    CONSTRAINT ck_fact_accident_usagers
        CHECK (nombre_usagers >= nombre_victimes)
);

CREATE INDEX IF NOT EXISTS ix_fact_accident_date
    ON dw.fact_accident(date_key);
CREATE INDEX IF NOT EXISTS ix_fact_accident_horaire
    ON dw.fact_accident(horaire_key);
CREATE INDEX IF NOT EXISTS ix_fact_accident_localisation
    ON dw.fact_accident(localisation_key);
CREATE INDEX IF NOT EXISTS ix_fact_accident_route
    ON dw.fact_accident(route_key);
CREATE INDEX IF NOT EXISTS ix_fact_accident_circonstance
    ON dw.fact_accident(circonstance_key);
CREATE INDEX IF NOT EXISTS ix_fact_accident_millesime
    ON dw.fact_accident(millesime_source);

COMMENT ON TABLE dw.fact_accident IS 'Une ligne par accident corporel BAAC.';
COMMENT ON COLUMN dw.fact_accident.num_acc IS 'Identifiant métier BAAC de l accident.';
COMMENT ON COLUMN dw.fact_accident.nombre_lieux_associes IS 'Nombre de lignes lieux reçues pour l accident.';
COMMENT ON COLUMN dw.fact_accident.voie_principale IS 'Voie sélectionnée par la règle déterministe de priorité.';

