CREATE TABLE IF NOT EXISTS audit.etl_run (
    run_id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_name          varchar(100) NOT NULL,
    started_at             timestamptz NOT NULL DEFAULT current_timestamp,
    finished_at            timestamptz,
    status                 varchar(20) NOT NULL DEFAULT 'RUNNING',
    start_year             smallint,
    end_year               smallint,
    message                text,
    CONSTRAINT ck_etl_run_status
        CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED'))
);

CREATE TABLE IF NOT EXISTS audit.etl_volume (
    volume_id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                 bigint NOT NULL REFERENCES audit.etl_run(run_id),
    stage_name             varchar(100) NOT NULL,
    object_name            varchar(150) NOT NULL,
    source_year            smallint,
    row_count              bigint NOT NULL CHECK (row_count >= 0),
    recorded_at            timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS audit.quality_result (
    quality_result_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                 bigint NOT NULL REFERENCES audit.etl_run(run_id),
    check_code             varchar(100) NOT NULL,
    check_name             varchar(250) NOT NULL,
    severity               varchar(20) NOT NULL,
    status                 varchar(20) NOT NULL,
    actual_value           numeric,
    expected_value         numeric,
    details                text,
    checked_at             timestamptz NOT NULL DEFAULT current_timestamp,
    CONSTRAINT ck_quality_severity
        CHECK (severity IN ('INFO', 'WARNING', 'ERROR')),
    CONSTRAINT ck_quality_status
        CHECK (status IN ('PASS', 'FAIL'))
);

CREATE TABLE IF NOT EXISTS audit.rejected_row (
    rejected_row_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                 bigint NOT NULL REFERENCES audit.etl_run(run_id),
    source_file            varchar(255) NOT NULL,
    source_year            smallint,
    source_row_number      bigint,
    business_key           varchar(255),
    rejection_code         varchar(100) NOT NULL,
    rejection_reason       text NOT NULL,
    raw_payload            jsonb,
    rejected_at            timestamptz NOT NULL DEFAULT current_timestamp
);

